stages:
- name: 阶段一
  steps:
  - runScriptConfig:
      image: v4ehxdz8.mirror.aliyuncs.com/library/busybox:latest
      shellScript: |-
        whoami
        ls -lrt
        pwd
        echo "hello world"
timeout: 60
notification: {}
