stages:
- name: 阶段一
  steps:
  - runScriptConfig:
      image: v4ehxdz8.mirror.aliyuncs.com/library/busybox:latest
      shellScript: whoami
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/django-demo:latest
timeout: 60
notification: {}
