stages:
- name: 阶段一
  steps:
  - runScriptConfig:
      image: v4ehxdz8.mirror.aliyuncs.com/library/busybox:latest
      shellScript: |-
        whoami
        ls -lrt
        pwd
        echo "hello world"
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: library/example:latest
      registry: 127.0.0.1:34682
timeout: 60
notification: {}
